### ISSUE TITLE
Initial Setup Error

### ISSUE THREAD

**Issue by Jordonbc** [Jordonbc/GlassOS#1]
There appears to be an error with the startup script.
Here is the error code:

Traceback (most recent call last):
  File "C:/Users/Jordon/PycharmProjects/Glass_OS V 2.0.0/run.pyw", line 8, in <module>
    from GlassOS import boot
  File "C:\Users\Jordon\PycharmProjects\Glass_OS V 2.0.0\GlassOS\boot.py", line 61, in <module>
    from GlassOS.System.glass import *
  File "C:\Users\Jordon\PycharmProjects\Glass_OS V 2.0.0\GlassOS\System\glass.py", line 518, in <module>
    active = open("active", "r").read()
FileNotFoundError: [Errno 2] No such file or directory: 'active'

**Comment by Jordonbc** [comment]
This is Fixed with the latest version
